# Generated by Django 5.1.6 on 2025-02-08 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragChatBot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LangchainPgCollection',
        ),
        migrations.DeleteModel(
            name='LangchainPgEmbedding',
        ),
    ]
